var s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var d=a.toLowerCase(),c=window.document,b=c.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var e=c.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=c.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+d+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";e.appendChild(f);b.insertBefore(e,c.head);
a=7==f["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),c=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),b=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,e;c<a?(e=a-c,c+=e,b+=CANVAS_WIDTH/CANVAS_HEIGHT*e):b<d&&(e=d-b,b+=e,c+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-c/2;var f=d/2-b/2,h=CANVAS_WIDTH/b;if(f*h<-EDGEBOARD_X||e*h<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),
b=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,e=(a-c)/2,f=(d-b)/2,h=CANVAS_WIDTH/b;s_iOffsetX=-1*f*h;s_iOffsetY=-1*e*h;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",b+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=c,s_oStage.scaleX=s_oStage.scaleY=Math.min(b/CANVAS_WIDTH,c/CANVAS_HEIGHT));
0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}function createBitmap(a,d,c){var b=new createjs.Bitmap(a),e=new createjs.Shape;d&&c?e.graphics.beginFill("#fff").drawRect(0,0,d,c):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=e;return b}function createSprite(a,d,c,b,e,f){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-c,-b,e,f);a.hitArea=d;return a}
function randomFloatBetween(a,d,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(c))}function shuffle(a){for(var d=a.length,c,b;0!==d;)b=Math.floor(Math.random()*d),--d,c=a[d],a[d]=a[b],a[b]=c;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var c="",c=10>d?c+("0"+d+":"):c+(d+":");return 10>a?c+("0"+a):c+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var d=Array.prototype.slice.call(arguments);return a.sort(function(a,b){for(var e=d.slice(),f=e.shift();a[f]==b[f]&&e.length;)f=e.shift();return a[f]==b[f]?0:a[f]>b[f]?1:-1})};function roundDecimal(a,d){var c=Math.pow(10,d);return Math.round(c*a)/c}function tweenVectors(a,d,c,b){b.set(a.getX()+c*(d.getX()-a.getX()),a.getY()+c*(d.getY()-a.getY()));return b}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var b=d[c].split("=");if(b[0]==a)return b[1]}}
function CSpriteLibrary(){var a,d,c,b,e,f;this.init=function(h,l,q){c=d=0;b=h;e=l;f=q;a={}};this.addSprite=function(c,b){a.hasOwnProperty(c)||(a[c]={szPath:b,oSprite:new Image},d++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){b.call(f);++c===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=768,EDGEBOARD_X=400,EDGEBOARD_Y=0,FONT1="OpenSans-BoldItalic",FONT2="Digital-7",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ROYAL_FLUSH=0,STRAIGHT_FLUSH=
1,FOUR_OF_A_KIND=2,FULL_HOUSE=3,FLUSH=4,STRAIGHT=5,THREE_OF_A_KIND=6,TWO_PAIR=7,JACKS_OR_BETTER=8,HIGH_CARD=9,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,SUIT_HEARTS=0,SUIT_DIAMONDS=1,SUIT_CLUBS=2,SUIT_SPADES=3,CARD_WIDTH=154,CARD_HEIGHT=240,BET_TYPE,TOTAL_MONEY,NUM_BETS=5,WIN_COMBINATIONS=9,COMBO_PRIZES,AUTOMATIC_RECHARGE,WIN_OCCURRENCE,GAME_CASH,MIN_WIN,NUM_HAND_FOR_ADS;
TEXT_GAMEOVER="GAME OVER";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_WIN="WIN";TEXT_MONEY="MONEY";TEXT_DEAL="DEAL";TEXT_BET_ONE="BET ONE";TEXT_MAX_BET="BET MAX";TEXT_RECHARGE="RECHARGE";TEXT_EXIT="EXIT";TEXT_DRAW="DRAW";TEXT_NO_WIN="NO WIN";TEXT_CURRENCY="$";TEXT_COMBO="Royal Flush;Straight Flush;Four of a Kind;Full House;Flush;Straight;Three of a Kind;Two Pairs;Jacks or Better".split(";");TEXT_CONGRATULATIONS="Congratulations!";TEXT_SHARE_1="You collected <strong>";TEXT_SHARE_2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_3="My score is ";TEXT_SHARE_4=" points! Can you do better?";
function CPreloader(){var a,d,c,b,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));e.addChild(f);c=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));c.x=761;c.y=CANVAS_HEIGHT-99;e.addChild(c);a=976;b=new createjs.Shape;b.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(761,CANVAS_HEIGHT-99,1,30);e.addChild(b);c.mask=b;d=new createjs.Text("0%","30px "+FONT1,"#fff");d.x=800;d.y=CANVAS_HEIGHT-105;d.textAlign="center";d.textBaseline="middle";e.addChild(d)};this.refreshLoader=function(c){d.text=
c+"%";c=Math.floor(c*a/100);b.graphics.clear();b.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(561,CANVAS_HEIGHT-99,c,30)};this._init()}
function CMain(a){var d,c=0,b=0,e=STATE_LOADING,f,h,l;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};
this.soundLoaded=function(){c++;h.refreshLoader(Math.floor(c/b*100));c===b&&this.removePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/card.ogg","card"),
createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/lose.ogg","lose"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/card.mp3","card"),
createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/lose.mp3","lose"),createjs.Sound.registerSound("./sounds/press_hold.mp3","press_hold")),b+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg",
"./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("hold",
"./sprites/hold.png");s_oSpriteLibrary.addSprite("logo_game","./sprites/logo_game.png");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.png");s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("big_display","./sprites/big_display.png");s_oSpriteLibrary.addSprite("selection","./sprites/selection.png");s_oSpriteLibrary.addSprite("card_selection","./sprites/card_selection.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=
function(){c++;h.refreshLoader(Math.floor(c/b*100));c===b&&this.removePreloader()};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.removePreloader=function(){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=
STATE_MENU};this.gotoGame=function(){l=new CGame(f);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;
s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&l.update();s_oStage.update(a)}};s_oMain=this;f=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oSoundTrack;
function CTextButton(a,d,c,b,e,f,h,l){var q,m,p,r,g,n,v,u,w,t;this._init=function(a,c,b,d,e,f,l,h){q=!1;r=[];g=[];t=h;v=createBitmap(b);m=b.width;p=b.height;h=Math.ceil(l/20);u=new createjs.Text(d,"bold "+l+"px "+e,"#000000");var A=u.getBounds();u.textAlign="center";u.textBaseline="alphabetic";u.x=b.width/2+h;u.y=Math.floor(b.height/2)+A.height/3+h;w=new createjs.Text(d,"bold "+l+"px "+e,f);w.textAlign="center";w.textBaseline="alphabetic";w.x=b.width/2;w.y=Math.floor(b.height/2)+A.height/3;n=new createjs.Container;
n.x=a;n.y=c;n.regX=b.width/2;n.regY=b.height/2;n.cursor="pointer";n.addChild(v,u,w);t.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");t.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){q=!1;v.filters=[];v.cache(0,0,m,p)};this.disable=function(){q=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);v.filters=[new createjs.ColorMatrixFilter(a)];v.cache(0,0,m,p)};this._initListener=function(){oParent=this;n.on("mousedown",
this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){r[a]=c;g[a]=b};this.buttonRelease=function(){q||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),n.scaleX=1,n.scaleY=1,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(g[ON_MOUSE_UP]))};this.buttonDown=function(){q||(n.scaleX=.9,n.scaleY=.9,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){n.x=a;n.y=c};this.changeText=function(a){w.text=a;u.text=a};this.setX=
function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,d,c,b,e,f,h,l);return this}
function CGfxButton(a,d,c){var b,e,f,h,l,q=[],m;this._init=function(a,c,d){b=!1;h=[];l=[];e=d.width;f=d.height;m=createBitmap(d);m.x=a;m.y=c;m.regX=d.width/2;m.regY=d.height/2;m.cursor="pointer";s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,c,b){h[a]=c;l[a]=b};this.addEventListenerWithParams=function(a,c,b,d){h[a]=c;l[a]=b;q=d};this.buttonRelease=function(){b||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],q))};this.buttonDown=function(){b||(m.scaleX=.9,m.scaleY=.9,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],q))};this.setPosition=function(a,c){m.x=a;m.y=c};this.setX=function(a){m.x=a};this.setY=function(a){m.y=
a};this.enable=function(){b=!1;m.filters=[];m.cache(0,0,e,f)};this.disable=function(){b=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);m.filters=[new createjs.ColorMatrixFilter(a)];m.cache(0,0,e,f)};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,d,c);return this}
function CToggle(a,d,c,b){var e,f,h,l;this._init=function(a,c,b,d){f=[];h=[];var g=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});e=d;l=createSprite(g,"state_"+e,b.width/2/2,b.height/2,b.width/2,b.height);l.x=a;l.y=c;l.stop();l.cursor="pointer";s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};
this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){f[a]=c;h[a]=b};this.setActive=function(a){e=a;l.gotoAndStop("state_"+e)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;l.gotoAndStop("state_"+e);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],e)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};
this.setPosition=function(a,c){l.x=a;l.y=c};this._init(a,d,c,b)}
function CMenu(){var a,d,c,b,e,f;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(c);var h=s_oSpriteLibrary.getSprite("but_menu_bg");b=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,h,TEXT_PLAY,"Arial","#ffffff",40,s_oStage);b.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-h.width/4-10,d=h.height/2+10,e=new CToggle(CANVAS_WIDTH-h.width/2+
20,h.height/2+20,h,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),s_oSoundTrack.setVolume(1);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},500).call(function(){f.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){b.unload();b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(c);c=null;s_oStage.removeChild(f);
s_oMenu=f=null};this.refreshButtonPos=function(c,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||e.setPosition(a-c,b+d)};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var d,c,b,e,f,h,l,q,m,p,r,g=[],n,v,u,w,t,x,y,k;this._init=function(){s_oPayTableSettings=new CPayTableSettings;b=TOTAL_MONEY;e=GAME_CASH;w=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(w);k=new createjs.Container;k.x=600;k.y=530;s_oStage.addChild(k);x=new CPayTable(550,149);d=!1;r=h=q=l=0;f=parseFloat(BET_TYPE[l]*(q+1));x.setCreditColumn(q);p=STATE_GAME_WAITING_FOR_BET;t=new CInterface(b,BET_TYPE[l]);y=new CGameOver;v=new CGameSettings;u=new CHandEvaluator;
m=0;n=[];n=v.getShuffledCardDeck();MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*f*(q+1);this.placeFakeCardForStarting();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oSoundTrack.setVolume(.5)};this.unload=function(){t.unload();y.unload();s_oStage.removeAllChildren()};this.resetHand=function(){m=h=0;n=[];n=v.getShuffledCardDeck();for(var a=0;a<g.length;a++)g[a].reset();t.resetHand();x.resetHand();this.checkMoney();d=!1;p=STATE_GAME_WAITING_FOR_BET};this.checkMoney=function(){b<f&&(q=l=0,f=parseFloat(BET_TYPE[l]*
(q+1)),b<f?this._gameOver():(t.refreshMoney(b,f),t.refreshBet(BET_TYPE[l])))};this.changeState=function(a){};this.placeFakeCardForStarting=function(){for(var a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],
card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],
card_4_K:[51],back:[52]}},c=0,b=0;5>b;b++){var d=new createjs.SpriteSheet(a),d=createSprite(d,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);d.x=c;d.y=0;d.shadow=new createjs.Shadow("#000000",5,5,5);k.addChild(d);c+=180}};this.dealCards=function(){if(!(d||0>=b)){d=!0;k.removeAllChildren();if((e<MIN_WIN?WIN_OCCURRENCE+1:Math.floor(101*Math.random()))>WIN_OCCURRENCE){do this._createCard();while(u.evaluate(g)<HIGH_CARD);c=!1}else this._createCard(),c=!0;b-=f;b=parseFloat(b.toFixed(2));e+=
f;t.refreshMoney(b,f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");p=STATE_GAME_DEAL}};this._createCard=function(){for(var a=0;a<g.length;a++)g[a].unload();a=0;g=[];for(var c=0;5>c;c++){var b=new CCard(a,0,k,n[m].fotogram,n[m].rank,n[m].suit);b.addEventListener(ON_CARD_SHOWN,this._onCardShown);b.addEventListener(ON_CARD_HIDE,this._onCardHide);g.push(b);m++;this._checkDeckLength();a+=180;b.showCard()}};this.drawCards=function(){if(!d){d=!0;!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("card");for(var a=g.length,c=0;c<g.length;c++)!1===g[c].isHold()&&(g[c].hideCard(),a--);a===g.length&&(p=STATE_GAME_DRAW,this._onCardShown())}};this._checkDeckLength=function(){m>=n.length&&(n=v.getShuffledCardDeck(),m=0)};this.assignWin=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win");for(var c=u.getSortedHand(),d=0;d<g.length;d++)for(var k=0;k<c.length;k++)if(c[k].rank===g[d].getRank()&&c[k].suit===g[d].getSuit()){g[d].highlight();
break}x.showWinAnim(q,a);h=s_oPayTableSettings.getWin(q,a)*f;b+=h;b=parseFloat(b.toFixed(2));e-=h;t.refreshWin(h);t.refreshMoney(b,f)};this.recharge=function(){b=TOTAL_MONEY;x.setCreditColumn(q);this.checkMoney();t.refreshMoney(b,f);t.refreshBet(BET_TYPE[l]);y.hide()};this._gameOver=function(){y.show()};this.onCardSelected=function(a){p===STATE_GAME_CHOOSE_HOLD&&a.toggleHold()};this._onCardShown=function(){if(p!==STATE_GAME_CHOOSE_HOLD){switch(p){case STATE_GAME_DEAL:p=STATE_GAME_CHOOSE_HOLD;t.setState(p);
break;case STATE_GAME_DRAW:var a=u.evaluate(g);t.setState(p);a!==HIGH_CARD?s_oGame.assignWin(a):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("lose"),t.showLosePanel());r++;r===NUM_HAND_FOR_ADS?(r=0,$(s_oMain).trigger("save_score",[b]),$(s_oMain).trigger("show_interlevel_ad")):r===NUM_HAND_FOR_ADS-1&&$(s_oMain).trigger("share_event",[b]);p=STATE_GAME_EVALUATE;break;case STATE_GAME_EVALUATE:t.setState(p)}d=!1}};this._onCardHide=function(){if(p!==STATE_GAME_DRAW){p=STATE_GAME_DRAW;
if(c){var a=0;do{s_oGame._changeCardValue();var b=u.evaluate(g),d;d=b===HIGH_CARD?0:COMBO_PRIZES[b];a++}while((b===HIGH_CARD||e<d)&&5E3>a);if(5E3<=a){do s_oGame._changeCardValue(),b=u.evaluate(g);while(b<HIGH_CARD);c=!1}}else{do s_oGame._changeCardValue(),b=u.evaluate(g);while(b<HIGH_CARD)}for(a=0;5>a;a++)g[a].setHold(!1)}};this._changeCardValue=function(){for(var a=0;5>a;a++)!1===g[a].isHold()&&(g[a].changeInfo(n[m].fotogram,n[m].rank,n[m].suit),g[a].showCard(),m++,this._checkDeckLength())};this._onButDealRelease=
function(){switch(p){case STATE_GAME_WAITING_FOR_BET:this.dealCards();break;case STATE_GAME_CHOOSE_HOLD:this.drawCards();break;case STATE_GAME_EVALUATE:this.resetHand(),this.dealCards()}};this._onButLeftRelease=function(){if(!(0===l||d||p!==STATE_GAME_WAITING_FOR_BET&&p!==STATE_GAME_EVALUATE)){MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1];l--;var a=parseFloat(BET_TYPE[l]*(q+1));b<a||(f=a,t.refreshMoney(b,f),t.refreshBet(BET_TYPE[l]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*f*(q+1))}};this._onButRightRelease=
function(){if(!(l===BET_TYPE.length-1||d||p!==STATE_GAME_WAITING_FOR_BET&&p!==STATE_GAME_EVALUATE)){l++;var a=parseFloat(BET_TYPE[l]*(q+1));b<a||(f=a,t.refreshMoney(b,f),t.refreshBet(BET_TYPE[l]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*f*(q+1))}};this._onButBetOneRelease=function(){if(!(d||p!==STATE_GAME_WAITING_FOR_BET&&p!==STATE_GAME_EVALUATE)){q++;q===NUM_BETS&&(q=0);var a=parseFloat(BET_TYPE[l]*(q+1));b<a||(f=a,t.refreshMoney(b,f),x.setCreditColumn(q),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-
1]*f*(q+1))}};this._onButBetMaxRelease=function(){if(!(d||p!==STATE_GAME_WAITING_FOR_BET&&p!==STATE_GAME_EVALUATE)){d=!0;q=NUM_BETS-1;var a=parseFloat(BET_TYPE[l]*(q+1));b<a?this._gameOver():(f=a,t.refreshMoney(b,f),x.setCreditColumn(q),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*f*(q+1),this.resetHand(),this.dealCards())}};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session")};this.update=function(){};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;GAME_CASH=a.game_cash;
BET_TYPE=a.bets;COMBO_PRIZES=a.combo_prizes;TOTAL_MONEY=a.money;AUTOMATIC_RECHARGE=a.recharge;NUM_HAND_FOR_ADS=a.num_hand_before_ads;this._init()}var s_oGame,s_oPayTableSettings;
function CInterface(a,d){var c,b,e,f,h,l,q,m,p,r,g,n,v,u,w,t;this._init=function(a,d){var k=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-k.width/2-2;b=k.height/2+2;h=new CGfxButton(c,b,k,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=h.getX()-k.width,f=k.height/2+2,g=new CToggle(e,f,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);k=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
k.x=480;k.y=25;s_oStage.addChild(k);k=new createjs.Text(TEXT_WIN,"21px "+FONT1,"#fff");k.x=490;k.y=32;k.textAlign="center";k.textBaseline="middle";s_oStage.addChild(k);k=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));k.x=480;k.y=93;s_oStage.addChild(k);k=new createjs.Text(TEXT_BET,"21px "+FONT1,"#fff");k.x=490;k.y=100;k.textAlign="center";k.textBaseline="middle";s_oStage.addChild(k);k=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));k.x=470;k.y=687;s_oStage.addChild(k);k=new createjs.Text(TEXT_MONEY,
"21px "+FONT1,"#fff");k.x=490;k.y=695;k.textAlign="center";k.textBaseline="middle";s_oStage.addChild(k);n=new createjs.Text(a.toFixed(2)+TEXT_CURRENCY,"bold 29px "+FONT2,"#ffde00");n.x=590;n.y=CANVAS_HEIGHT-65;n.textAlign="center";s_oStage.addChild(n);u=new createjs.Text(d.toFixed(2)+TEXT_CURRENCY,"bold 29px "+FONT2,"#ffde00");u.x=590;u.y=110;u.textAlign="center";s_oStage.addChild(u);v=new createjs.Text("0"+TEXT_CURRENCY,"bold 29px "+FONT2,"#ffde00");v.x=590;v.y=40;v.textAlign="center";s_oStage.addChild(v);
k=createBitmap(s_oSpriteLibrary.getSprite("big_display"));k.x=770;k.y=686;s_oStage.addChild(k);w=new createjs.Text(d.toFixed(2)+TEXT_CURRENCY,"bold 40px "+FONT2,"#ffde00");w.x=840;w.y=700;w.textAlign="center";s_oStage.addChild(w);var k=s_oSpriteLibrary.getSprite("logo_game"),z=createBitmap(k);z.x=CANVAS_WIDTH/2;z.y=17;z.regX=k.width/2;s_oStage.addChild(z);k=s_oSpriteLibrary.getSprite("but_left");l=new CGfxButton(744,722,k,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButLeftRelease,this);k=s_oSpriteLibrary.getSprite("but_right");
q=new CGfxButton(930,722,k,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButRightRelease,this);k=s_oSpriteLibrary.getSprite("but_game_bg");m=new CTextButton(1040,716,k,TEXT_BET_ONE,FONT1,"#ffffff",23,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onButBetOneRelease,this);p=new CTextButton(1190,716,k,TEXT_MAX_BET,FONT1,"#ffffff",23,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButBetMaxRelease,this);r=new CTextButton(1340,716,k,TEXT_DEAL,FONT1,"#ffffff",30,s_oStage);r.addEventListener(ON_MOUSE_UP,
this._onButDealRelease,this);t=new createjs.Container;t.visible=!1;t.x=710;t.y=500;s_oStage.addChild(t);k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,500,100);t.addChild(k);k=new createjs.Text(TEXT_NO_WIN,"50px "+FONT1,"#fff");k.x=250;k.y=20;k.textAlign="center";t.addChild(k);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();l.unload();q.unload();m.unload();p.unload();r.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;
s_oInterface=null};this.refreshButtonPos=function(a,d){h.setPosition(c-a,d+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(e-a,d+f)};this.setState=function(a){switch(a){case STATE_GAME_CHOOSE_HOLD:r.changeText(TEXT_DRAW);break;case STATE_GAME_DRAW:case STATE_GAME_EVALUATE:r.changeText(TEXT_DEAL)}};this.resetHand=function(){this.refreshWin(0);t.visible=!1};this.refreshMoney=function(a,c){n.text=a.toFixed(2)+TEXT_CURRENCY;u.text=c.toFixed(2)+TEXT_CURRENCY};this.refreshWin=function(a){v.text=
a.toFixed(2)+TEXT_CURRENCY};this.refreshBet=function(a){w.text=a.toFixed(2)+TEXT_CURRENCY};this.showLosePanel=function(){t.visible=!0};this._onButLeftRelease=function(){s_oGame._onButLeftRelease()};this._onButRightRelease=function(){s_oGame._onButRightRelease()};this._onButBetOneRelease=function(){s_oGame._onButBetOneRelease()};this._onButBetMaxRelease=function(){s_oGame._onButBetMaxRelease()};this._onButDealRelease=function(){s_oGame._onButDealRelease()};this._onExit=function(){s_oGame.onExit()};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init(a,d);return this}var s_oInterface=null;
function CGameSettings(){var a,d;this._init=function(){var c=-1;a=[];for(var b=0;52>b;b++){var d=(b+1)%13;1===d?(d=14,c++):0===d&&(d=13);a.push({fotogram:b,rank:d,suit:c})}};this.timeToString=function(a){a=Math.round(a/1E3);var b=Math.floor(a/60);a-=60*b;var d="",d=10>b?d+("0"+b+":"):d+(b+":");return 10>a?d+("0"+a):d+a};this.getShuffledCardDeck=function(){for(var c=[],b=0;b<a.length;b++)c[b]=a[b];for(d=[];0<c.length;)d.push(c.splice(Math.round(Math.random()*(c.length-1)),1)[0]);return d};this.getCardValue=
function(a){return(void 0)[a]};this._init()}
function CCard(a,d,c,b,e,f){var h,l,q,m,p,r,g,n,v,u,w,t;this._init=function(a,c,b,d,e,f){h=!1;w=b;l=d;q=e;m=f;b=s_oSpriteLibrary.getSprite("card_spritesheet");b=new createjs.SpriteSheet({images:[b],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],
card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],
back:[52]}});g=createSprite(b,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);g.x=a;g.y=c;g.stop();g.shadow=new createjs.Shadow("#000000",5,5,5);w.addChild(g);b=s_oSpriteLibrary.getSprite("hold");n=createBitmap(b);n.regX=b.width/2;n.x=a;n.y=c+76;n.visible=!1;w.addChild(n);b=s_oSpriteLibrary.getSprite("card_selection");u=createBitmap(b);u.x=a;u.y=c;u.regX=b.width/2;u.regY=b.height/2;u.visible=!1;w.addChild(u);v=new createjs.Shape;v.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(a-
CARD_WIDTH/2,c-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);v.on("click",this._onSelected);v.cursor="pointer";w.addChild(v);p=[];r=[]};this.unload=function(){v.off("click",this._onSelected);w.removeChild(g)};this.reset=function(){h=!1;u.visible=!1;g.shadow=new createjs.Shadow("#000000",5,5,5)};this.addEventListener=function(a,b,c){p[a]=b;r[a]=c};this.changeInfo=function(a,b,c){l=a;q=b;m=c};this.setValue=function(){g.gotoAndStop(l);var a=this;createjs.Tween.get(g).to({scaleX:1},200).call(function(){a.cardShown()})};
this.setHold=function(a){h=a;n.visible=h};this.toggleHold=function(){createjs.Tween.hasActiveTweens(g)||(h=!h,n.visible=h,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_hold"))};this.showCard=function(){var a=this;createjs.Tween.get(g).to({scaleX:.1},200).call(function(){a.setValue()})};this.hideCard=function(){var a=this;createjs.Tween.get(g).to({scaleX:.1},200).call(function(){a.setBack()})};this.setBack=function(){g.gotoAndStop("back");var a=this;createjs.Tween.get(g).to({scaleX:1},
200).call(function(){a.cardHidden()})};this.cardShown=function(){p[ON_CARD_SHOWN]&&p[ON_CARD_SHOWN].call(r[ON_CARD_SHOWN])};this.cardHidden=function(){p[ON_CARD_HIDE]&&p[ON_CARD_HIDE].call(r[ON_CARD_HIDE],this)};this.highlight=function(){g.shadow=new createjs.Shadow("#fff000",0,0,15);u.visible=!0};this._onSelected=function(){s_oGame.onCardSelected(t)};this.getRank=function(){return q};this.getSuit=function(){return m};this.getFotogram=function(){return l};this.isHold=function(){return h};t=this;this._init(a,
d,c,b,e,f)}
function CGameOver(){var a,d,c,b;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);var e=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(e);a=new createjs.Text(TEXT_GAMEOVER,"bold 32px Arial","#fff");a.textAlign="center";a.x=CANVAS_WIDTH/2;a.y=290;a.shadow=new createjs.Shadow("#000000",2,2,2);b.addChild(a);d=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,"Arial","#fff",14,b);d.addEventListener(ON_MOUSE_UP,this._onRecharge,
this);c=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,"Arial","#fff",14,b);c.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){d.unload();c.unload()};this.show=function(){b.visible=!0};this.hide=function(){b.visible=!1};this._onRecharge=function(){AUTOMATIC_RECHARGE&&s_oGame.recharge();$(s_oMain).trigger("recharge")};this._onExit=function(){$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init()}
function CPayTable(a,d){var c,b,e,f,h;this._init=function(a,d){c=0;h=new createjs.Container;h.x=a;h.y=d;s_oStage.addChild(h);var m=createBitmap(s_oSpriteLibrary.getSprite("paytable"));h.addChild(m);var m=278,p=4;b=[];for(var r=0;r<NUM_BETS;r++){var g=createBitmap(s_oSpriteLibrary.getSprite("selection"));g.visible=!1;g.x=m;g.y=p;h.addChild(g);b.push(g);m+=100}m=275;p=27;f=[];for(r=0;r<WIN_COMBINATIONS;r++)g=new createjs.Text(TEXT_COMBO[r],"bold 22px Arial","#fff000"),g.x=m,g.y=p,g.textAlign="right",
g.textBaseline="middle",h.addChild(g),p+=22,f[r]=g;m=375;e=[];for(r=0;r<NUM_BETS;r++){p=27;e[r]=[];for(g=0;g<WIN_COMBINATIONS;g++){var n=new createjs.Text(s_oPayTableSettings.getWin(r,g),"bold 22px Arial","#fff000");n.x=m;n.y=p;n.textAlign="right";n.textBaseline="middle";h.addChild(n);p+=22;e[r][g]=n}m+=100}};this.resetHand=function(){createjs.Tween.removeAllTweens();for(var a=0;a<NUM_BETS;a++)for(var b=0;b<WIN_COMBINATIONS;b++)e[a][b].alpha=1;for(a=0;a<WIN_COMBINATIONS;a++)f[a].alpha=1};this.setCreditColumn=
function(a){for(var c=0;c<NUM_BETS;c++)b[c].visible=!1;b[a].visible=!0};this.showWinAnim=function(a,b){var d=this;createjs.Tween.get(e[a][b]).to({alpha:c},100).call(function(){d.showWinAnim(a,b)});createjs.Tween.get(f[b]).to({alpha:c},100);c=1===c?0:1};this._init(a,d)}function CPayTableSettings(){var a;this._init=function(){a=[];for(var d=0;d<NUM_BETS;d++){a[d]=[];for(var c=0;c<WIN_COMBINATIONS;c++)a[d][c]=COMBO_PRIZES[c]*(d+1)}};this.getWin=function(d,c){return a[d][c]};this._init()}
function CHandEvaluator(){var a,d;this.evaluate=function(c){a=[];for(var b=0;b<c.length;b++)a[b]={rank:c[b].getRank(),suit:c[b].getSuit()};a.sort(this.compareRank);d=[0,1,2,3,4];return this.rankHand()};this.rankHand=function(){if(this._checkForRoyalFlush())return ROYAL_FLUSH;if(this._checkForStraightFlush())return STRAIGHT_FLUSH;if(this._checkForFourOfAKind())return FOUR_OF_A_KIND;if(this._checkForFullHouse())return FULL_HOUSE;if(this._checkForFlush())return FLUSH;if(this._checkForStraight())return STRAIGHT;
if(this._checkForThreeOfAKind())return THREE_OF_A_KIND;if(this._checkForTwoPair())return TWO_PAIR;if(this._checkForOnePair())return JACKS_OR_BETTER;this._identifyHighCard();return HIGH_CARD};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return a[0].rank===a[3].rank?(a.splice(4,1),d.splice(4,1),!0):a[1].rank===a[4].rank?(a.splice(0,
1),d.splice(0,1),!0):!1};this._checkForFullHouse=function(){return a[0].rank===a[1].rank&&a[2].rank===a[4].rank||a[0].rank===a[2].rank&&a[3].rank===a[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return a[0].rank===a[1].rank&&a[0].rank===a[2].rank?(a.splice(3,1),a.splice(3,1),d.splice(3,1),d.splice(3,1),!0):a[1].rank===a[2].rank&&a[1].rank===a[3].rank?(a.splice(0,
1),a.splice(3,1),d.splice(0,1),d.splice(3,1),!0):a[2].rank===a[3].rank&&a[2].rank===a[4].rank?(a.splice(0,1),a.splice(0,1),d.splice(0,1),d.splice(0,1),!0):!1};this._checkForTwoPair=function(){return a[0].rank===a[1].rank&&a[2].rank===a[3].rank?(a.splice(4,1),d.splice(4,1),!0):a[1].rank===a[2].rank&&a[3].rank===a[4].rank?(a.splice(0,1),d.splice(0,1),!0):a[0].rank===a[1].rank&&a[3].rank===a[4].rank?(a.splice(2,1),d.splice(2,1),!0):!1};this._checkForOnePair=function(){for(var c=0;4>c;c++)if(a[c].rank===
a[c+1].rank&&a[c].rank>CARD_TEN){var b=a[c],e=a[c+1];a=[];a.push(b);a.push(e);d=[c,c+1];return!0}return!1};this._identifyHighCard=function(){for(var c=0;4>c;c++)a.splice(0,1)};this._isFlush=function(){return a[0].suit===a[1].suit&&a[0].suit===a[2].suit&&a[0].suit===a[3].suit&&a[0].suit===a[4].suit?!0:!1};this._isRoyalStraight=function(){return a[0].rank===CARD_TEN&&a[1].rank===CARD_JACK&&a[2].rank===CARD_QUEEN&&a[3].rank===CARD_KING&&a[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){var c=a[0].rank+
1===a[1].rank&&a[1].rank+1===a[2].rank&&a[2].rank+1===a[3].rank;return c&&a[0].rank===CARD_TWO&&a[4].rank===CARD_ACE?!0:c&&a[3].rank+1===a[4].rank?!0:!1};this.compareRank=function(a,b){return a.rank<b.rank?-1:a.rank>b.rank?1:0};this.getSortedHand=function(){return a};this.getCardIndexInCombo=function(){return d}};
